baseurl: https://example.org/
title: Urban Stack
theme: hugo-creative-portfolio-theme
languageCode: en-us
disqusShortname: ''
googleAnalytics: ''
publishDir: 'docs'
params:
  copyright: '&copy;2022 Urban Stack'
  description: Describe your website
  email: you@yoursite.com
  navlinks:
    - home: yes
      name: Projects
      url: portfolio/
    - name: People
      url: about/
  sidebarAbout:
    - Urban Stack is a planning and design research lab that uncovers and 
      makes visible the political, social, economic, and institutional 
      processes that shape the built environment.
    - We are based at the Harvard Graduate School of Design
  social:
    github: https://github.com/urban-stack
  style: default
